### ISSUE TITLE
Rayleigh Fading to be implemented more efficiently

### ISSUE THREAD

**Issue by MattCarrickPL** [TorchDSP/torchsig#124]
def rayleigh_fading() operates at an oversampling rate of 100x in order to achieve the proper coherence bandwidth. the taps are created at fs, then interpolated using interp1d() to 100fs. the input signal is then interpolated by 100, the weights are applied, and then decimated by 100. running at 100x oversampling requires a bunch of computational time, and data generation can be improved by making this function more efficient.

option 1: calculate the minimum interpolation value needed to implement the precision required for the coherence bandwidth

option 2: it _should_ be possible to resample the rayleigh weights themselves, rather than doing all of the computation against the input signal. an integer number of weights N for the rayleigh channel means we can only support coherence bandwidths of fs/(N-1). however, we _should_ be able to apply an interpolator to resample the weights such that we can have non-integer based delays which would support non-integer coherence bandwidths other than fs/(N-1).

**Comment by gvanhoy** [comment]
I believe the plan was to put things in a dsp module and generally accelerate interpolation.

**Comment by MattCarrickPL** [comment]
Old issue, closing out.
