### ISSUE TITLE
Adjust DatasetReader/DatasetWriter Concepts for Extensibility

### ISSUE THREAD

**Issue by gvanhoy** [TorchDSP/torchsig#128]
A ```Reader``` class has the responsibility of producing ```SignalData``` from a source (file, network, generated).

A ```Dataset``` class has the responsibility of arranging ```SignalData``` acquired from ```Reader(s)``` using a constructed index to be transformed. 

A ```Transform``` class has the responsibility of transforming ```SignalData.```

A ```Writer``` class has the responsibility of preparing ```SignalData``` for storage (file, network). 

Raw Data -> Reader -> Dataset -> Transforms -> Writer -> Storage

**Comment by MattCarrickPL** [comment]
Old issue, closing out
