### ISSUE TITLE
Unify data and meta-data transforms

### ISSUE THREAD

**Issue by gvanhoy** [TorchDSP/torchsig#129]
We want to be able to compose a Transform pipeline that contains transforms with multiple potential implementations and be able to intelligently choose which one to use. 

The implementations could vary in:

1. Parameter type (SignalData (and extensions) vs np.ndarray)
2. Algorithm (fftconvolve vs convolve)
3. Device (CPU vs GPU)

We want the transforms pipeline to transparently handle this with an optional way to explicitly specify which one to use. 

We also want developers to be able to know how to make multiple implementations of a transform.

```python

class TransformInterface:
    def _signal_data(self, data):
        raise NotImplementedError

    def _numpy(self, data):
        raise NotImplementedError

    def __call__(self, data):
        if isinstance(data, SignalData):
            return self._signal_data(data)

        if isinstance(data, np.ndarray):
            return self._numpy(data)

class RandomAWGN(TransformInterface):
    def _signal_data(self, data: SignalData):
        print("Adding noise to SignalData")

    def _numpy(self, data: np.ndarray):
        print("Adding noise to np.ndarray")

class Dataset:
    def __init__(self, transforms):
        self.transforms = transforms

    def __getitem__(self, index: int):
        data = self.index[index]

        for transform in self.transforms:
            data = transform(data)

        return data
````

**Comment by gvanhoy** [comment]
Another idea was brought up here -- if data/meta-data could be toted around in a class that's lighter-weight that SignalData, then transforming numpy arrays or other data containers in and out of SignalData should be fine to do intelligently. Doing ```TypedDicts``` is one alternative.

**Comment by MattCarrickPL** [comment]
Old issue, closing out
