### ISSUE TITLE
Emit warning when generating a static dataset based on available disk space

### ISSUE THREAD

**Issue by jcr0269** [TorchDSP/torchsig#148]
One of the example files call for a 1 terabyte of memory in the initialization. This seems to be a bit excessive, also the system is not adaptable to windows. 

In 01_exaple_modulation_dataset lmdb on line 163 allocates a map_size of 1e12. Also in torchsig/datasets/sig53.py on line 91 there is the same call. 

Writer.py needs to be adjusted for the windows bug.

**Comment by gvanhoy** [comment]
This static dataset is about ~600GB large. So, it would be tough to fit on that machine. That's just the clean Sig53 dataset as well. Probably it would be better to make a notebook that just uses the dataset that's generated on the fly.

**Comment by gvanhoy** [comment]
I think this will be best covered in #169 and #170. Emitting a warning when there's not enough disk-spakce might be too complicated to support on multiple OS's.

**Comment by ereoh** [comment]
I believe we fixed a bunch of dataset generation issues in the latest release ([0.5.3](https://github.com/TorchDSP/torchsig/tree/v0.5.3)). Closing this issue for now, but if issue persists feel free to reopen it.
