### ISSUE TITLE
Use spawn or fork depending on OS

### ISSUE THREAD

**Issue by jcr0269** [TorchDSP/torchsig#149]
In torchsig/utils/wirter.py on line 53 you use multiprocessing_context=torch.multiprocessing.get_context("fork") 

This is a UNIX based call. Although this can be faster, the issue with this is that it is specific to only one operating system and becomes unstable with more complex issues. This is a possible future pipeline issue and I would recommend moving to spawn which is universal across all platforms and is more robust.

**Comment by gvanhoy** [comment]
I like using the best one per-platform using ```os.name``` :).

**Comment by MattCarrickPL** [comment]
Only targeting linux-based environments for now. Closing.
