### ISSUE TITLE
Having a better read me

### ISSUE THREAD

**Issue by jcr0269** [TorchDSP/torchsig#150]
There is a lot of potential in torchsig. Having a better break down of what each program does or is intended to do would be a huge help. This would allow devs to better utilize the tools and offer more constructive insights on what they are seeing. Such as if this is currently only designed for Linux in the beta version, adding that to the documentation.

**Comment by gvanhoy** [comment]
Could definitely use a facelift in the case of the RTD docs and general improvements in the case of the README.

**Comment by lboegner** [comment]
@jcr0269 - Really appreciate the engagement lately :)

Personally, I think three things should happen (in increasing level of effort):
1. Our `README.md` should link our website, [torchsig.com](torchsig.com), where users can find more information in a different style.
2. Our [RTD site](https://torchsig.readthedocs.io/en/latest/index.html) (which is linked in the README) needs to be fixed. Right now, if anyone follows the link, the main page on RTD opens but navigating around shows only titles in most places (at least when I tried just now).
3. We should expand the RTD and include notebook examples as part of our documentation there (for datasets, transforms, and models). We previously included (and still have a few) notebooks in our examples directory which were easy and quick ways to visually learn more, but maintaining executed NBs in git is not great. Through sphinx NB plug-ins, we should be able to include non-executed notebooks in git to avoid the binary data while still having the nice visuals display in documentation (see [here](https://docs.readthedocs.io/en/stable/guides/jupyter.html#creating-galleries-of-examples-using-notebooks)).

**Comment by MattCarrickPL** [comment]
Release of new notebooks is an attempt to improve understanding of torchsig for new users. May revisit README and documentation later, but closing this issue for now.
