### ISSUE TITLE
os has no attribute named root

### ISSUE THREAD

**Issue by jcr0269** [TorchDSP/torchsig#151]
scripts/generate_sig53.py 
- on line 43 based on the error I recieved

if not os.root.isdir(root):
    os.mkdir(root)

Should be:

if not os.path.isdir(root):
    os.mkdir(root)

**Comment by MattCarrickPL** [comment]
This has been patched in v0.4.1 (https://github.com/TorchDSP/torchsig/tree/v0.4.1) and later versions
