### ISSUE TITLE
directory does not exist 00_example_sig53

### ISSUE THREAD

**Issue by jcr0269** [TorchDSP/torchsig#152]
There is probably a much better way to do this, but the file does not just exist to store the figures. 
Option 1:  Just create the folder. 

Option 2:  Under torchsig/utils/writer.py on line 86 add a check for the path.
self.path = path
if not os.path.exists(self.path):
 ---> os.makedirs(self.path)

**Comment by gvanhoy** [comment]
This folder is created in 0.5.x, 0.4.1, and in develop, closing.
