### ISSUE TITLE
Running examples in examples/ directory produces error

### ISSUE THREAD

**Issue by MattCarrickPL** [TorchDSP/torchsig#159]
Running the examples in examples/ produces an error
$ python3 00_example_sig53_dataset.py 

Traceback (most recent call last):
  File "00_example_sig53_dataset.py", line 10, in <module>
    from torchsig.datasets.modulations import ModulationsDataset
  File "/home/USER/.local/lib/python3.8/site-packages/torchsig/datasets/modulations.py", line 19, in <module>
    from torchsig.transforms.target_transforms import (
ImportError: cannot import name 'DescToClassIndex' from 'torchsig.transforms.target_transforms' (/home/USER/.local/lib/python3.8/site-packages/torchsig/transforms/target_transforms/__init__.py)

However, running the examples from the top-level directory works:
$ python3 examples/00_example_sig53_dataset.py 

Users will naturally cd into examples/ and run scripts from there. Any way to resolve the import issue?

**Comment by gvanhoy** [comment]
I can transform these back into notebooks.

**Comment by MattCarrickPL** [comment]
Is transformation back into notebooks the only way to resolve?
