### ISSUE TITLE
Online data generation and training

### ISSUE THREAD

**Issue by biasedlearner** [TorchDSP/torchsig#161]
Is there an example script that does online data generation on the fly and training on it rather than first creating data, saving in memory, and using that for training?
Is it possible to share how you experimented with the RadioML2018 dataset?

**Comment by gvanhoy** [comment]
Hm, not just a plain example for that, but a few pieces of the code will get you there like:

```python
from torchsig.datasets.modulations import ModulationsDataset
from torchsig.datasets import conf
import os

config = conf.Sig53CleanTrainConfig
dataset = ModulationsDataset(
    level=config.level,
    num_samples=config.num_samples,
    num_iq_samples=config.num_iq_samples,
    use_class_idx=config.use_class_idx,
    include_snr=config.include_snr,
    eb_no=config.eb_no,
)
# at this point, you can get data with dataset[index] or wrap the dataset in a data loader.
```

Would an example beyond this be helpful?

**Comment by gvanhoy** [comment]
More examples to come, but you can find this in the examples folder in the v0.4.2 branch. Here's a [direct link](https://github.com/TorchDSP/torchsig/blob/v0.4.2/examples/03_otf_sig53_classifier.ipynb).
