### ISSUE TITLE
Make RandomDistribution a native type

### ISSUE THREAD

**Issue by gvanhoy** [TorchDSP/torchsig#164]
Docstrings are rather bloated when describing what is essentially just a random distribution. We should describe this more succinctly by have a basic data type ```RandomDistribution``` that has its own documentation and implemented a general __call__ method.

**Comment by gvanhoy** [comment]
Currently the random distribution also slows many things down. It should be made into a class variable

**Comment by gvanhoy** [comment]
Closed by #202

**Comment by MattCarrickPL** [comment]
Old issue, closing out
