### ISSUE TITLE
Consider normalization of bandwidths across FSK/PSK

### ISSUE THREAD

**Issue by gvanhoy** [TorchDSP/torchsig#195]
The normalized bandwidth of FSK's appears to be fs/8 and PSK's is fs/2

**Comment by MattCarrickPL** [comment]
I believe the bandwidth for G/FSK is defined via samples per symbol here:

fsk_dataset = FSKDataset(
            modulations=fsks,
            num_iq_samples=num_iq_samples,
            num_samples_per_class=num_samples_per_class,
            **iq_samples_per_symbol=8,**
            random_data=random_data,
            random_pulse_shaping=random_pulse_shaping,
            **kwargs,
        )
        gfsks_dataset = FSKDataset(
            modulations=gfsks,
            num_iq_samples=num_iq_samples,
            num_samples_per_class=num_samples_per_class,
            **iq_samples_per_symbol=8,**
            random_data=random_data,
            random_pulse_shaping=random_pulse_shaping,
            **kwargs,
        )

https://github.com/TorchDSP/torchsig/blob/main/torchsig/datasets/synthetic.py#L183

The 8 samples per symbol is used as a bandwidth measure which is then transformed internally to the FSK modulator such it has the proper bandwidth.

**Comment by MattCarrickPL** [comment]
Old issue, closing out
