### ISSUE TITLE
No Documentation for Creation of All Pretrained Models Found at https://torchsig.com/dist/downloads.html  

### ISSUE THREAD

**Issue by sciafri** [TorchDSP/torchsig#206]
**Describe the bug**
After creating the datasets, I would like to recreate the pretrained models. However, it's not clear how to do so for all datasets and model combinations listed at: https://torchsig.com/dist/downloads.html. Could you please describe where I might be able to find this information to generate all pretrained models listed on https://torchsig.com/dist/downloads.html ? 

After a quick read through of the code, I don't see where any of that is documented. There are two places which hint at somethings missing in the repository:

1. scripts/train_sig53.py only details how to train efficientnet on sig53. Do I use this script as a template and modify this script for each of the pretrained models?

2. As it is right now, models/iq_models and models/spectrogram_models only lists efficientnet, xcit, and detr. Yet on the downloads there are additionally: YOLOv5, Mask2Former, PSPNet. How are those pretrained models supported by the code? Did you simply just modify the train_sig53.py file to have those models in the template? I want to make sure I'm getting exactly the pretrained models created on that website, so confirmation about this would be helpful.

Thank you.

**Comment by MattCarrickPL** [comment]
We are in the process of updating the set of pretrained models with new ones and much of the documentation about how to train models is within the new example notebooks
