### ISSUE TITLE
Documentation on signal parameters for signal generation and create user friendly section to change parameters. 

### ISSUE THREAD

**Issue by ven716** [TorchDSP/torchsig#224]
Looking at when creating the datasets for the classifier and detector models, it seems very difficult for users to discern certain characteristics like center frequency, samples per symbol, and others. Is it possible to change these parameters? If so, can there be a feature that lets the user input their needed parameters.

**Comment by MattCarrickPL** [comment]
Dataset generation is randomized behind the scenes to cover a broad range of center frequencies, bandwidths, modulations, etc.  and is not user controllable by design.
