### ISSUE TITLE
"pip install ." does not work with Python 3.10.12

### ISSUE THREAD

**Issue by mcmillan03** [TorchDSP/torchsig#227]
**Describe the bug**
I am running in Ubuntu 22.04 LTS VM with python 3.10.12.

**To Reproduce**
1. clone torchsig repo
2. cd torchsig (into repo)
3. pip3 install .
4. See error below

**Expected behavior**

I expect it to install any missing dependencies, then build wheels for torchsig and lit and then install those. Instead it is building UNKNOWN wheels.

**Screenshots**

```
~/..../torchsig (main) $ pip3 install .
Processing /home/smcmillan/Codesign/pytorch-resnet/torchsig
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: UNKNOWN
  Building wheel for UNKNOWN (pyproject.toml) ... done
  Created wheel for UNKNOWN: filename=UNKNOWN-0.0.0-py3-none-any.whl size=1781 sha256=2a80ecc9c9a11c05b5804fc9586580b768cb3994d3dbb2717105541811f008b1
  Stored in directory: /tmp/pip-ephem-wheel-cache-6eoswxs4/wheels/80/77/c2/7857e24549e69f113278740dbd5d1958be091fc131e1e29070
Successfully built UNKNOWN
Installing collected packages: UNKNOWN
  Attempting uninstall: UNKNOWN
    Found existing installation: UNKNOWN 0.0.0
    Uninstalling UNKNOWN-0.0.0:
      Successfully uninstalled UNKNOWN-0.0.0
Successfully installed UNKNOWN-0.0.0
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 LTS (running in a VM)
 - Python version: 3.10.12

**Additional context**
When running in Ubuntu 20.04LTS with python 3.8.10, I don't have this problem

**Comment by MattCarrickPL** [comment]
Have had large code changes since issue submitted, unclear if still a problem. Closing.
