### ISSUE TITLE
Invalid argument for DatasetCreator().__init__()

### ISSUE THREAD

**Issue by IsaiahHarvi** [TorchDSP/torchsig#235]
When running `generate_wideband_sig53.py`, a type error is raised when initializing DatasetCreator with the `num_workers` argument.

The issued command:
 python3 generate_wideband_sig53.py --root=data/sig53_wb --all=True

Response:
```
generate_wideband_sig53.py", line 33, in generate
    creator = DatasetCreator(
              ^^^^^^^^^^^^^^^
TypeError: DatasetCreator.__init__() got an unexpected keyword argument 'num_workers'
```

After removing that argument and rerunning, the dataset began to generate properly.

_Ubuntu, Torchsig v0.4.1_

**Comment by TorchDSP** [comment]
These issues have been resolved in updated main.
