### ISSUE TITLE
NumPy 1.x cannot be run in NumPy 2.0.0 as it may crash; .../examples/00_example_sig53_dataset.ipynb

### ISSUE THREAD

**Issue by springyworks** [TorchDSP/torchsig#238]
**Describe the bug**
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

**To Reproduce**
using venv
git clone
pip install -e . 
run example notebook ; 00_example_sig53_dataset.ipynb

**Expected behavior**
no errors

**Screenshots**
![image](https://github.com/user-attachments/assets/ad567579-0bcd-4cd8-96e3-8a88714e90d5)

**Desktop **
 - OS: Ubuntu24 on WSL2
-  IDE : vscode-insiders

**Additional context**
file with pip installed packages and version numbers
[torchsig_packages_versions.txt](https://github.com/user-attachments/files/16191590/torchsig_packages_versions.txt)

cheers , [PE1BFE](https://www.qrz.com/db/pe1bfe)
73 ko

**Comment by nsbruce** [comment]
the numpy version isn't fixed in the pyproject.toml so I fixed this by doing a `pip install "numpy<2"`

**Comment by springyworks** [comment]
that worked. it is related to the version of opencv-python .
