### ISSUE TITLE
Git LFS exceeded data quota

### ISSUE THREAD

**Issue by jogomojo** [TorchDSP/torchsig#246]
**Describe the bug**  
When cloning the `torchsig` repository an error occurs related to Git LFS preventing the download of certain large files. The error message indicates that the repository has exceeded its data quota.

**To Reproduce**  
1. Clone the repo  
   ```bash
   git clone https://github.com/TorchDSP/torchsig.git
   ```
2. Wait for the repository to be cloned.
3. Observe the error message during the download process for LFS-managed files.

**Expected behavior**  
The repository should clone successfully, with all files, including those managed by Git LFS, should be downloaded without errors.

**Error Message**  
```
Downloading gr-spectrumdetect/examples/detect.pt (273 MB)
Error downloading object: gr-spectrumdetect/examples/detect.pt (16a7c7b): Smudge error: Error downloading gr-spectrumdetect/examples/detect.pt (16a7c7b49b6ee04c7bcaee593977dcfb27ea7486c8ccaebe1ee03ca418fed6af): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to /home/jng/scratch/torchsig/.git/lfs/logs/20240923T231017.135572472.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: gr-spectrumdetect/examples/detect.pt: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Desktop (please complete the following information):**  
- OS: Ubuntu 20.04.5
- Git Version: 2.34.1
- Git LFS Version: 3.0.2

**Additional context**  
- Cloning with `GIT_LFS_SKIP_SMUDGE=1` skips the download of LFS files, but the missing files are needed for the example project.
- Suggest hosting the larger files in an additional location (e.g. archive.org)

**Comment by MattCarrickPL** [comment]
Thanks for reporting @jogomojo. I personally wasn't able to recreate the problem, but we are looking at it internally and working on a fix.

**Comment by MattCarrickPL** [comment]
Please let us know if you have any more problems @jogomojo

**Comment by jogomojo** [comment]
@MattCarrickPL the problem seems to be fixed now, thank you.
