### ISSUE TITLE
Important Request: No LFS in Git repo

### ISSUE THREAD

**Issue by sciafri** [TorchDSP/torchsig#247]
Hi,

It seems the latest commits are using LFS. 

That significantly makes it harder to use this repo.

Is there a way to remove the need for LFS files in this repo?

Thank you.

**Comment by MattCarrickPL** [comment]
Taking a look now. If you have recommendations or a suggestion solution on how to do so, please let me know.

**Comment by ereoh** [comment]
Hi, I've been working on the fix. Let me know if the latest commit fixed the issue?

**Comment by ereoh** [comment]
@sciafri let me know if the issue persists. Closing issue for now.
