### ISSUE TITLE
Issue with LFS still (seeming not purged from history)

### ISSUE THREAD

**Issue by agm-eratosth** [TorchDSP/torchsig#248]
Hi,

What steps did you take in https://github.com/TorchDSP/torchsig/issues/247 to resolve the LFS file issue? Still having problems with the repo due to the LFS.

You should first check:

`git lfs ls-files`

to see if any files still exist.

Use https://github.com/newren/git-filter-repo the git filter-repo tool should remove the files from the history. I think you will need to run something like this:

`git filter-repo --replace-refs delete-no-add --strip-blobs-bigger-than 0M`

I can also try this at some point, especially if you know what commands you previously ran. Hopefully you get to it before me. 

Thank you!

**Comment by ereoh** [comment]
Hi, thanks for making the issue. I followed [GitHub's guide](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository) for removing files from LFS.
```
git filter-repo --invert-paths --path torchsig/gr-spectrumdetect/examples/detect.pt
```

I have also run your command and pushed it to the repo. Let me know if that worked or if you also have a fix.

Thanks!

**Comment by ereoh** [comment]
Closing for now. Feel free to reopen if problem persists.
