### ISSUE TITLE
Broken cupy import when using GPU

### ISSUE THREAD

**Issue by drojas-ai** [TorchDSP/torchsig#26]
Cupy is imported as 'xp' in synthetic.py and wideband.py, causing the assignment xp = cp to fail later in the code. I think the intent is to import it as cp. 

synthetic.py
https://github.com/TorchDSP/torchsig/blob/909deb36fb4ea04fd4caa558206eef4cd02b12cb/torchsig/datasets/synthetic.py#L13
https://github.com/TorchDSP/torchsig/blob/909deb36fb4ea04fd4caa558206eef4cd02b12cb/torchsig/datasets/synthetic.py#L283

wideband.py
https://github.com/TorchDSP/torchsig/blob/909deb36fb4ea04fd4caa558206eef4cd02b12cb/torchsig/datasets/wideband.py#L14
https://github.com/TorchDSP/torchsig/blob/909deb36fb4ea04fd4caa558206eef4cd02b12cb/torchsig/datasets/wideband.py#L256

**Comment by gvanhoy** [comment]
Will work on this in #39
