### ISSUE TITLE
Which package versions does the code support?

### ISSUE THREAD

**Issue by yatsir** [TorchDSP/torchsig#51]
Hi,
What is the python/torch/torchvision versions that the code support?  

I"m getting this issue:
 OSError: /home/usr/anaconda3/lib/python3.9/site-packages/torch/lib/../../nvidia/cublas/lib/libcublas.so.11: undefined symbol: cublasLtGetStatusString, version libcublasLt.so.11

Thanks.

**Comment by gvanhoy** [comment]
Hello,

We intend to support Python 3.7 to 3.11.

This looks like an issue with cudatoolkit/Anaconda/CUDA drivers to me.

**Comment by yatsir** [comment]
OK,
Thanks.
