### ISSUE TITLE
"pip install ." doesn't install 

### ISSUE THREAD

**Issue by thildebrant** [TorchDSP/torchsig#63]
I tried to install today, then tried to run 00_example _sig53_dataset.py.
It errored out saying:
Traceback (most recent call last):
  File "~/torchsig/examples/00_example_sig53_dataset.py", line 8, in <module>
    from torchsig.utils.visualize import IQVisualizer, SpectrogramVisualizer
ModuleNotFoundError: No module named 'torchsig'

To reproduce
on a clean Ubuntu-22.04 image (WSL2), I installed python3-pip
then git clone https://github.com/TorchDSP/torchsig.git
cd torchsig
~/torchsig$ pip install .
Defaulting to user installation because normal site-packages is not writeable
Processing /home/rfml/torchsig
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: UNKNOWN
  Building wheel for UNKNOWN (pyproject.toml) ... done
  Created wheel for UNKNOWN: filename=UNKNOWN-0.0.0-py3-none-any.whl size=1781 sha256=e2342c977887edc1d4ba88e9fa97f8df084732439bcd89f9bc42a361edc0bfcf
  Stored in directory: /tmp/pip-ephem-wheel-cache-e8gqc7yu/wheels/d7/45/19/1a2488076fc711f0225342f63115e57818593ac2f598ba9438
Successfully built UNKNOWN
Installing collected packages: UNKNOWN
  Attempting uninstall: UNKNOWN
    Found existing installation: UNKNOWN 0.0.0
    Uninstalling UNKNOWN-0.0.0:
      Successfully uninstalled UNKNOWN-0.0.0
Successfully installed UNKNOWN-0.0.0

**Comment by gvanhoy** [comment]
@thildebrant Does this apply here? https://github.com/pypa/setuptools/issues/3269#issuecomment-1254507377

**Comment by thildebrant** [comment]
yes, good catch.
export DEB_PYTHON_INSTALL_LAYOUT=deb_system 
then install . pulls down everything. 
Thanks
