### ISSUE TITLE
DatasetCreator generates more data than samples in the dataset

### ISSUE THREAD

**Issue by EvanSpector** [TorchDSP/torchsig#68]
It seems to generate (num_workers + batch_size) times more data than is specified in the dataset num_samples.

**Comment by gvanhoy** [comment]
@EvanSpector Thanks for making the issue. Any information on the platform?

**Comment by EvanSpector** [comment]
Thanks for your work on this repo

AlmaLinux 8.6
CPU: AMD Ryzen 9 3900X

**Comment by gvanhoy** [comment]
Although I suspected this could be an issue, I cannot reproduce this using different multiprocessing contexts or hard-coding different ```num_workers``` or ```batch_size``` within the PyTorch DataLoader.

**Comment by gvanhoy** [comment]
Closing because I cannot reproduce.
