### ISSUE TITLE
pip install issues(?)

### ISSUE THREAD

**Issue by ven716** [TorchDSP/torchsig#69]
Followed the steps to pip install TorchSig however, I can not run any of the scripts since there are no models(example 5) that were pip installed or other dependencies like cm_plotter (example 1).

**Comment by gvanhoy** [comment]
Please install from the [release branch v0.2.0](https://github.com/TorchDSP/torchsig/releases/tag/v0.2.0). The main branch is likely to be a bit unstable; especially in regards to the Wideband work.
