### ISSUE TITLE
Examine OFDM Generation for potential speedups for Sig53

### ISSUE THREAD

**Issue by gvanhoy** [TorchDSP/torchsig#75]

**Comment by MattCarrickPL** [comment]
Possible speed up, removal of double for loop:

            for subcarrier_idx in range(bursty.shape[0]):
                on = original_on
                for time_idx in range(bursty.shape[1]):
                    if time_idx % burst_dur == 0:
                        on = not on
                    if (not on) and (
                        time_idx >= burst_region_start and time_idx <= burst_region_stop
                    ):
                        bursty[subcarrier_idx, time_idx] = 0 + 1j * 0

https://github.com/TorchDSP/torchsig/blob/develop/torchsig/datasets/synthetic.py#L677
