### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'examples/sig53/sig53_clean_train

### ISSUE THREAD

**Issue by jiaduob** [TorchDSP/torchsig#87]
**Describe the bug**
I have run the 00_example_sig53_dataset.py and 02_example_sig53_classifier.py, but there are similar errors that they can't generate the  datasets and file, and give me a same error:FileNotFoundError: [Errno 2] No such file or directory: 'examples/sig53/sig53_clean_train'.
It's strange that I could run them to generate the datasets and file before the utils/writer.py was online.

**Environment:**
 - Ubuntu 7.5.0-3ubuntu1~18.04
 - python 3.9.16 remote-environment
 - torch 1.13.0+cu116

**Stacktrace**

`Traceback (most recent call last):
  File "/mnt/boxb/ljy/classification/atest/02_sig53_classifier.py", line 65, in <module>
    creator = DatasetCreator(ds, seed=12345678, path="examples/sig53/sig53_clean_train")
  File "/home/zzzk/anaconda3/envs/ljy/lib/python3.9/site-packages/torchsig/utils/writer.py", line 137, in __init__
    self.writer = LMDBDatasetWriter(path=path)
  File "/home/zzzk/anaconda3/envs/ljy/lib/python3.9/site-packages/torchsig/utils/writer.py", line 79, in __init__
    self.env = lmdb.Environment(path, subdir=True, map_size=int(1e12), max_dbs=2)

  FileNotFoundError: [Errno 2] No such file or directory: 'examples/sig53/sig53_clean_train'`

**Comment by gvanhoy** [comment]
This should be resolved by creating a folder called "sig53" inside of the examples folder. I will push an update soon.
